export function generateELTACSVHeader(): string {
  return [
    "Country",
    "Service",
    "ID",
    "Given Name",
    "Surname",
    "Organisation Name",
    "Registration Number",
    "Pick Up Point",
    "Parcel Locker",
    "Street Name",
    "Street Number",
    "Extension",
    "Street Specification",
    "Postal Code",
    "District Number",
    "Town",
    "Region / State",
    "District",
    "County",
    "Telephone Number",
    "Email",
    "Reference No",
    "Weight (in Kg)",
    "Length (in cm)",
    "Width (in cm)",
    "Height (in cm)",
    "Quantity",
    "COD (In €)",
    "Insured Value (In €)",
    "Gift",
    "Documents",
    "Commercial sample",
    "Returned goods",
    "Sale Of Goods",
    "Other",
    "Explanation",
    "Detailed description of contents",
    "Quantity",
    "Net weight (in Kg)",
    "Value (in €)",
    "HS tariff number",
    "Country of origin of goods",
    "Detailed description of contents",
    "Quantity",
    "Net weight (in Kg)",
    "Value (in €)",
    "HS tariff number",
    "Country of origin of goods",
    "Detailed description of contents",
    "Quantity",
    "Net weight (in Kg)",
    "Value (in €)",
    "HS tariff number",
    "Country of origin of goods",
    "Detailed description of contents",
    "Quantity",
    "Net weight (in Kg)",
    "Value (in €)",
    "HS tariff number",
    "Country of origin of goods",
    "Detailed description of contents",
    "Quantity",
    "Net weight (in Kg)",
    "Value (in €)",
    "HS tariff number",
    "Country of origin of goods",
    "Comments",
    "Importer's reference",
    "Importer's telephone/fax/e-mail",
    "Licence No(s)",
    "Certificate No(s)",
    "Invoice No(s)",
  ].join(";");
}

export function generateELTACSVTail(
  countryIsEu: boolean | undefined,
  legalDocNumber?: string
): string {
  return !countryIsEu ? ";".repeat(30) + legalDocNumber : ";".repeat(36);
}
